### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere#227]
What are we doing about analytics? Are we migrating them? Are we continuing to track views and downloads?

## WDLL

* capture both page views for a work and number of times a file has been downloaded
* migrate existing analytics from files and works so that metrics remain consistent
* provide UI to view given metrics
* use Matomo for third-party integrations, if needed

## Questions

1. Do we want to have the same UI?

### Door Number One

Use Matomo with client-side to capture metrics and then download (nightly) for retention, similar to how we're doing it in Scholoarsphere 3

### Door Number Two

Use application code only to capture the page views and downloads. This could be done via log scraping or controllers incrementing request counts on resources.

**Comment by srerickson** [comment]
Yes, we need analytics. Ideally we can continue to track the analytics we're tracking now and migrate historical usage information from SS3.

Thank you for raising this issue.

**Comment by awead** [comment]
Thank @binkylush! She raised the issue during our "tour" meeting this morning.

**Comment by DanCoughlin** [comment]
At kickoff we've decided to implement Matomo/Piwik for analytics AND capturing views and downloads within the application and we will use our view and download count to show to the user. At a later point we may do more with Matomo/Piwik, for now we will use our own code for showing the user how many downloads they have.

**Comment by awead** [comment]
## TODO

- [x] Capture view and download statistics #381 
- [x] Migrate Analytics Data #379 
- [x] ~~Display results of work downloads and views~~

**Comment by awead** [comment]
I've removed the work downloads and views ticket.
